### ISSUE TITLE
Loopback Request

### ISSUE THREAD

**Issue by gerhardbeck** [lenasterg/ls-wp-ccsearch#2]
Hi,
I'm working with Wordpress 5.6 and the plugin produces an error:

`Deine Website konnte eine Loopback-Anfrage nicht abschließen
Loopback-Anfragen werden verwendet, um geplante Ereignisse auszuführen, und werden auch von den integrierten Editoren für Themes und Plugins verwendet, um die Stabilität des Codes zu überprüfen.

Die Loopback-Anfrage lieferte einen unerwarteten http-Statuscode, 404, es war nicht möglich zu bestimmen, ob dies verhindert, dass Funktionen wie erwartet funktionieren.
`

**Comment by lenasterg** [comment]
Hi, 
try the latest version from https://wordpress.org/plugins/ls-wp-ccsearch/
