### ISSUE TITLE
Register a block

### ISSUE THREAD

**Issue by vagelisp** [lenasterg/ls-wp-ccsearch#4]
related to PR #3

**Comment by lenasterg** [comment]
Hi. 
Έκανα revert το merge του PR γιατί εμφανίζει τα παρακάτω security risks:

[node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor ](https://github.com/lenasterg/ls-wp-ccsearch/security/dependabot/3)High
node-fetch (npm) · package-lock.json · #3 opened 32 minutes ago
[Uncontrolled Resource Consumption in markdown-it ](https://github.com/lenasterg/ls-wp-ccsearch/security/dependabot/2)Moderate
markdown-it (npm) · package-lock.json · #2 opened 32 minutes ago
[Inefficient Regular Expression Complexity in nth-check ](https://github.com/lenasterg/ls-wp-ccsearch/security/dependabot/1)Moderate
nth-check (npm) · package-lock.json · #1 opened 32 minutes ago

**Comment by vagelisp** [comment]
Καλησπέρα @lenasterg , αυτό είναι dependency του @wordpress/scripts δεν επηρεάζει σε κάτι το plugin και δεν υπάρχει fix.
 Για να μην "ενοχλεί" μπορείς να κάνεις το παρακάτω:

![Screen Shot 2022-02-10 at 1 28 44 PM](https://user-images.githubusercontent.com/9304640/153400021-27ac4480-73a5-4ada-8962-b55448bb598f.png)

Η περιμένεις μέχρι να βγει fix.
Εγώ έκανα ενα update στο block σήμερα το μετέφερα σ ενα folder για να είναι πιο συμμαζεμένο στο fork μου. 
Θα κάνω άλλο ένα PR, για να μπορέσεις να το τραβήξεις όποτε θελήσεις.

**Comment by lenasterg** [comment]
Merged
